parserOptions:
  # Trying to match node 5.5.x ES6 support
  ecmaVersion: 6
  ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    templateStrings: true
    destructuring: false  # @@GRR! doesn't seem to work
  sourceType: script  # TODO: module in client side

root: true

# prefer const
