parserOptions:
  # Trying to match node 6.4.0 ES6 support per http://node.green/
  ecmaVersion: 6
  ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    templateStrings: true
    destructuring: true
  sourceType: script  # TODO: module in client side

root: true

# prefer const
